import {SocialSharing} from "@ionic-native/social-sharing/ngx";
import {config} from "./config";

export class PropertyHelper {
  private socialSharing: SocialSharing;

  constructor() {
  }

  init(
    socialSharing: SocialSharing,
  ) {
    this.socialSharing = socialSharing;

    return this;
  }

  static getPropertyImage(property) {
    if (property.getPhotoUrl()) {
      return property.getPhotoUrl();
    }

    return 'assets/imgs/default_img.png';
  }

  showMapForLocation() {
  }

  async shareProperty(propertyId, user) {
    try {
      let msg = `Hello, ${user.name} thinks you might be interested in this property. ` +
          `This email was generated by R.E.Connect mobile app. ` +
        `Click the link below to see the information`;

      let options = {
        message: msg, // not supported on some apps (Facebook, Instagram)
        subject: 'Share Property', // fi. for email
        url: `${config.urlWebapp}/property/${propertyId}`,
      };

      const res = await this.socialSharing.shareWithOptions(options);

      console.log('Shared successfully', res);
    }
    catch (e) {
      console.log(e);
    }
  }
}
