import {SocialSharing} from "@ionic-native/social-sharing/ngx";
import {config} from "./config";

export class PropertyHelper {
  private socialSharing: SocialSharing;

  constructor() {
  }

  init(
    socialSharing: SocialSharing,
  ) {
    this.socialSharing = socialSharing;

    return this;
  }

  static getPropertyImage(property) {
    if (property.getPhotoUrl()) {
      return property.getPhotoUrl();
    }

    return 'assets/imgs/default_img.png';
  }

  showMapForLocation() {
  }

  async shareProperty(propertyId, user, toastCtrl) {
    try {
      let msg = `Hello, ${user.name} thinks you might be interested in this property. ` +
          `This email was generated by R.E.Connect mobile app. ` +
        `Click the link below to see the information <br />` +
        `<a href="${config.urlWebapp}/property/${propertyId}">${config.urlWebapp}/property/${propertyId}</a>`;

      const res = await this.socialSharing.shareViaEmail(
        msg,
        'Share Property',
        [],
      );

      console.log('Shared successfully', res);

      if (res) {
        // show notice
        const toast = await toastCtrl.create({
          color: 'dark',
          message: 'Email has been sent successfully',
          duration: 2000
        });
        toast.present();
      }
    }
    catch (e) {
      console.log(e);
    }
  }
}
